#!/bin/sh
set -x

url="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts"
tmpDir=/tmp/hosts
wget -nc -O "$tmpDir" "$url" \
    | grep '^0\.0\.0\.0' "$tmpDir" \
    | awk '{print "local-zone: \""$2"\" redirect\nlocal-data: \""$2" A 0.0.0.0\""}' \
    | sudo tee "/etc/unbound/adservers"

sudo systemctl restart unbound.service
